### ISSUE TITLE
 scrollview blocks after dragging

### ISSUE THREAD

**Issue by rosalin** [FokkeZB/nl.fokkezb.infiniteScroll#34]
scrollview hangs for 5-7 seconds after dragging, can you help me?

<code>
function myLoader(e, collection) {
     var ln = collection.models.length;

    collection.fetch({
    	// whatever your sync adapter needs to fetch the next page
        //data: { offset: ln },
        // don't reset the collection, but add to it
        add: true,
        query:"SELECT o.order_id, lower(o.status) AS status, strftime('%d/%m/%Y', o.date) AS date, o.partial_total, o.point_sale, c.name FROM orders AS o "+
        		"INNER JOIN customers AS c ON o.customer_id = c.customer_id ORDER BY o.date LIMIT 20 OFFSET "+ln,
        success: function (col) {
            // call done() when we received last page - else success()
            (col.models.length === ln) ? e.done() : e.success();
        },
        // call error() when fetch fails
        error: function(col) {
            // pass optional error message to display
            e.error(L('isError', 'Tap to try again...'));
        }
    });
}
</code>

**Comment by FokkeZB** [comment]
Please be more specific in what you mean by hanging. Maybe record a movie?

**Comment by rosalin** [comment]
Sorry. I will try to explain better. 
After updating the items in tableview when activityloader disappears tableview is blocked for a few seconds.

**Comment by FokkeZB** [comment]
I think this is when the list view is re-populated by Alloy based on the new contents of the collection. Is it a complex or long list you're working with?

**Comment by rosalin** [comment]
They are simple data. I'm working with 10 elements at a time. 
I plan to work directly with a global varialvel where I would store all my data, will it solve?

**Comment by FokkeZB** [comment]
I'm not sure if that's related. I guess you will need to profile your code step by step, finding out what exactly takes so much time. Please re-open if you find it's a bug at the widget's side.
