### ISSUE TITLE
Initial load doesn't call onEnd

### ISSUE THREAD

**Issue by filaruina** [FokkeZB/nl.fokkezb.infiniteScroll#36]
Hi,

The initial call to 
`$.is.load();`
Makes the loading show up but doesn't trigger the end event.
Althogh, If I don't call the initial load I get an empty list with the button to load more. If I click it the function that loads more is called normally.

Is it a bug with newer version of titanium/alloy?

My info:

SDK Version = 3.5.1.GA
Target Platform = android
Alloy Version = 1.5.1

Some simplified code:

Template:

    <Widget id="ptr" src="nl.fokkezb.pullToRefresh" onRelease="loadNewerMessages">
        <ListView id="contentList" defaultItemTemplate="messageTemplate">
            <Templates>
                <ItemTemplate name="unreadMessageTemplate">
                    <View class="item-block">
                        <Label bindId="topText" class="item-element item-top-text"></Label>
                        <Label bindId="titleText" class="item-element item-title"></Label>
                        <Label bindId="bottomText" class="item-element item-bottom-text"></Label>
                    </View>
                    <View class="item-shadow"></View>
                </ItemTemplate>
                <ItemTemplate name="readMessageTemplate">
                    <View class="item-block read-message">
                        <Label bindId="topText" class="item-element item-top-text"></Label>
                        <Label bindId="titleText" class="item-element item-title"></Label>
                        <Label bindId="bottomText" class="item-element item-bottom-text"></Label>
                    </View>
                    <View class="item-shadow"></View>
                </ItemTemplate>
            </Templates>
            <ListSection/>
            <Widget id="is" src="nl.fokkezb.infiniteScroll" onEnd="loadMoreMessages" />
        </ListView>
    </Widget>

Controller:

    $.is.init($.contentList);
    var loadMoreMessages = function(e) {
        XHR.get(
            'messages',
            {
                start: currentIndex,
                limit: listLimit
            },
            function(data) {
                currentIndex += listLimit;
    
                if (data.rows.length < listLimit) {
                    e.done();
                } else {
                    e.success();
                }
       
                $.contentList.sections[0].appendItems(data);
            }
        );
    };
    
    $.is.load();

**Comment by FokkeZB** [comment]
You should probably change `onRelease="loadNewerMessages"` to `onEnd="loadNewerMessages"`, like in the example form the readme.

**Comment by filaruina** [comment]
Think you looked at the other widget, pull to refresh. The code referencing infiniteScroll is:

`<Widget id="is" src="nl.fokkezb.infiniteScroll" onEnd="loadMoreMessages" />`

Once again, the problem happens on the initial load only. Clicking the "load more.." button works.

**Comment by filaruina** [comment]
I did a console.log on $ just before the trigger inside the widget

    $.trigger('end', {
      success: function(msg) {
        return state(exports.SUCCESS, msg);
      },
      error: function(msg) {
        return state(exports.ERROR, msg);
      },
      done: function(msg) {
        return state(exports.DONE, msg);
      },
    });

The results when the initial load is called contains a _callbacks that doesn't exist when I remove the initial load and press the button

    //The last part of console.log after pressing the button
    "SUCCESS": 1,
    "ERROR": 0,
    "DONE": -1,
    "_callbacks": {
        "end": {
            "tail": {},
            "next": {
                "next": {}
            }
        }
    }

    //The last part of console.log when using $.is.load() on startup
    "SUCCESS": 1,
    "ERROR": 0,
    "DONE": -1

**Comment by FokkeZB** [comment]
@filaruina that's because on tap, the event is passed directly to the load function:
https://github.com/FokkeZB/nl.fokkezb.infiniteScroll/blob/master/controllers/widget.js#L65

I'm really busy atm, but if you can send me a full test case (simple project) then I try to debug it this week.

**Comment by filaruina** [comment]
I've built a test case, with the `$.is.load()`

https://www.dropbox.com/s/8camikcu4ur5tdo/infiniteScrollTest.zip?dl=0

**Comment by FokkeZB** [comment]
The problem was that you uses `var foo = callback(){}` instead of `function foo(){}`. This caused the listener to be bound *after* you called $.is.load().

**Comment by filaruina** [comment]
It works! Think I'm too used to declaring functions that way in my webdev work.
Thanks! You think a note on that on the readme is useful or is that recommended in titanium and I missed it?

**Comment by FokkeZB** [comment]
I think if you'd open up the compiled controller in `Resources/android/alloy/controllers/index.js` before and after the change you'll understand. Kinda hard to explain. I will add a note though most people I think will declare functions the traditional way.
