### ISSUE TITLE
Android Gaps Solution: Scrolling up & down of 'heavy' Rows creates gaps between rows

### ISSUE THREAD

**Issue by yozef** [FokkeZB/nl.fokkezb.infiniteScroll#37]
If you're using this awesome module for Android *(iOS works great as-is)*, and your Rows creates **gaps** sometimes between the rows as you scroll up & down *(especially if you have images within your rows)*, the solution is to remove **borderRadius** (or set it to 0) and thats it!

Wasn't sure where to place this info, but surely will come handy to some.

**Comment by FokkeZB** [comment]
The borderRadius of what exactly?

**Comment by yozef** [comment]
The **borderRadius** of the **TableViewRow** *(if you're using TableViews)*

**Comment by FokkeZB** [comment]
That's not really related to the widget is it?

Do a search for `hasBorder` on https://github.com/appcelerator/titanium_mobile/blob/99bbb066dc1a4519933e57395d2028d3448b8fd5/android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java and you'll see that a border brings in many additional UI calculations.
