### ISSUE TITLE
Cannot publish app with new update, only works in simulator

### ISSUE THREAD

**Issue by ShapeShifters** [FokkeZB/nl.fokkezb.infiniteScroll#39]
I used the new update for ![TiCollectionView](https://github.com/mpociot/TiCollectionView). When i use this module with nl.fokkezb.infiniteScroll i cannot publish while it debugs and runs sucessfully only on simulator. While publishing with appcelerator studio i get **arm64 and armv7 error** and most times it throws **compileC error**. _Error only exists when using with TiCollectionView. **I think nl.fokkezb.infiniteScroll  does not supports TiCollectionView** in publish/release_

 
`[ERROR] : ** BUILD FAILED ** [ERROR] : The following build commands failed: [ERROR] : Ld build/HelloWorlder.build/Release-iphoneos/HelloWorld-universal.build/Objects-normal/armv7/HelloWorld normal armv7 [ERROR] : Ld build/HelloWorld.build/Release-iphoneos/HelloWorld-universal.build/Objects-normal/arm64/HelloWorld normal arm64 [ERROR] : (2 failures) TRACE | titanium exited with exit code 1 ERROR | Error: ti run exited with error code 1 at ChildProcess.<anonymous> (/Users/alex/.appcelerator/install/4.0.0/package/node_modules/appc-cli-titanium/plugins/run.js:84:66) at ChildProcess.emit (events.js:117:20) at Process.ChildProcess._handle.onexit (child_process.js:820:12)`

**Comment by FokkeZB** [comment]
@ShapeShifters it looks like the https://github.com/mpociot/TiCollectionView version you use does not support 64-bit, which is now required for iOS since beginning this year.

**Comment by ShapeShifters** [comment]
Thanks for replying Fokke. I have checked the module, and it has 64 bit support. I used **FokkeZB/ti-64** to check this. It shows support for all armv7s armv7 arm64 i386. I suppose compileC error comes if i'm using old sdk(3.5.1GA), while armv7 and arm64 error comes for newer sdk(4.0.1). In any case pusblish/release is not happening. AAre you able to clean publish using infiniteScroll & TiCollectionView?

**Comment by FokkeZB** [comment]
I haven't. I really don't think its related to this widget since that's all just JS. I'd try to open an issue at the module's repo. If you have a ZIP of a project that fails and the exact steps I can give it a go as well.

**Comment by ShapeShifters** [comment]
Hello fokke. Well you were right the problem is only in TiCollectionView. You can  just recreate this issue with a simple hello world program in alloy that titanium studio provies for new project, then add the TiCollectionView module in project and publish it. I assure you it'll fail to build in publish; while it'll build on simulator. Do let me know your results & if you were able to find a solution. Thanks!

**Comment by FokkeZB** [comment]
Well, I believe you for it that it is a module problem. So I'll close this issue and ask you to follow this up with https://github.com/mpociot/TiCollectionView

**Comment by ShapeShifters** [comment]
But your update is of no good with a non-working module. You're not even gonna try?!

**Comment by FokkeZB** [comment]
I'm very sorry but I'm in my last week before my vacation and I don't have time for it atm. And since it is a module problem, I assume @mpociot will look into it.

**Comment by mpociot** [comment]
Hello @ShapeShifters 
Which version of the module are you using? I'm regularly publishing apps with my module (for production - not simulator) without any problems.
Can you show me the complete log when building your project?
