### ISSUE TITLE
How can I change the text ?

### ISSUE THREAD

**Issue by DouglasHennrich** [FokkeZB/nl.fokkezb.infiniteScroll#40]
Hi, how can I change the Text ? "tap to load more..."
I have the same problem on your other widget... pull to refresh

Thanks

**Comment by FokkeZB** [comment]
I assume you tried this?
https://github.com/FokkeZB/nl.fokkezb.infiniteScroll#options

**Comment by DouglasHennrich** [comment]
Sorry... @_@ hahaha
and on this widget: https://github.com/FokkeZB/nl.fokkezb.pullToRefresh
is there any options there too?

Thanks

**Comment by FokkeZB** [comment]
No sorry, it hasn't. As you can see I create the `Ti.UI.RefreshControl` without any arguments:
https://github.com/FokkeZB/nl.fokkezb.pullToRefresh/blob/master/nl.fokkezb.pullToRefresh/controllers/widget.js#L26

You could do a PR for it to accept the `tintColor` and `title` params.
