### ISSUE TITLE
Remove footer when done? 

### ISSUE THREAD

**Issue by X-Tender** [FokkeZB/nl.fokkezb.infiniteScroll#46]
Note really a issue, but is it possible to remove the footer with the info text when done() is triggered?

**Comment by FokkeZB** [comment]
I wanted to do that, but in Android you cannot hide the footerView. It has been a long time ago, so if you find that you can, we can add that of course.

**Comment by X-Tender** [comment]
OK. I tryed to replace it with a 1px height view but oddly it still persist the same.

**Comment by FokkeZB** [comment]
Yes, that's what I found. Works fine on iOS :( See if you can find a JIRA ticket for a way to hide/remove the footerView and if there isn't one..please create and link from here.

**Comment by X-Tender** [comment]
OK. I achieved it via
$.isCenter.setHeight(0);
in your Widget.

**Comment by FokkeZB** [comment]
OK, can you do a PR and include a test in the test-branch:
https://github.com/FokkeZB/nl.fokkezb.infiniteScroll/tree/test

**Comment by X-Tender** [comment]
Sorry what? :)
I don't have any experience it tests and what is PR?
The "Souliton" is more like a workaround and would not work for everybody I think.

**Comment by FokkeZB** [comment]
Aha... a GitHub newbie! ;) You do use git (or svn or whatever) to version your projects I hope?
https://help.github.com/categories/bootcamp/ is a good start.
