### ISSUE TITLE
Nice to have: Example without models/collections but normal payloads

### ISSUE THREAD

**Issue by nuno** [FokkeZB/nl.fokkezb.infiniteScroll#49]
Really nice to have a example or sample without models/collections but normal payloads, special with ListView api.

**Comment by FokkeZB** [comment]
Something like this probably:

```
var page = 0;
var API = require('my-api');

function myLoader(e) {

    page++;

    API.getPage(page, function(err, results) {

        if (err) {
            return e.error(err);
        }

        if (results.length === 0) {
            return e.done();
        }

        $.myListView.sections[0].appendItems(results.map(function(result) {

            items.push({
                info: {
                    text: result.name
                }
            });

        }));

        e.success();
    });
}
```

**Comment by mnadeemughal** [comment]
Hi, 
I hope you will be fine. I am creating listview like below:


		for (var i = 0; i < data.length; i++) {
			dataItem.push({
				template : 'template',
				properties : {
					width : '97%',
					left : '1.5%',
					height : ht,
					top : '5dp',
					bottom : '2dp',
					borderRadius : 5,
					backgroundColor : 'white',
					//layout: "horizontal"
				},
				sIcon : {
					image : '/oilsthumbs/soicon' + iconCount + '.png',
				},
				sName : {
					text : data[i].NAME,
				},
				sAffinity : {
					text : "Affinitive For: " + data[i].AFFINITY_FOR
				}
			});
			iconCount++;

		}


	var section = Ti.UI.createListSection();
	section.items = (dataItem);
	var sections = [];
	sections.push(section);
	$.singleList.sections = sections;
Can you guide me how it will be implemented in this form. I am quite confused with it. :(

**Comment by FokkeZB** [comment]
Well it depends on where you get your data from how you handle the paging, but in the end after you have data to add you will use `appendItems()` on your section to add the new items to the section.

**Comment by mnadeemughal** [comment]
Firstly, Thank you for quick response. 
I am getting json from a local json file. Here is how I am getting data in the same controller to display in the list : 

var file = Titanium.Filesystem.getFile(Titanium.Filesystem.resourcesDirectory, '/datas/singleoils.json');
var preParsedData = file.read().text;
var parsedData = JSON.parse(preParsedData);
data = parsedData.singleoils;
$.is.init($.singleList);
var dataItem = [];

**Comment by mnadeemughal** [comment]
Hi,
Either the documentation isn't explained well (it is good only if developer is using models and collection to add data) or My understand is weak. In any case please review this comment and reply. 


Here is I am doing it with appendItems. 
 
 var data = [];
 data = parsedData.singleoils;      // This data object contains the parsed JSON data that I want to add in the list
 function myLoader(e) {

	if (j < data.length) {
		for (var i = j; i < j + 10; i++) {
			dataItem.push({
				template : 'template',
				properties : {
					width : '97%',
					left : '1.5%',
					height : ht,
					top : '5dp',
					bottom : '2dp',
					borderRadius : 5,
					backgroundColor : 'white',
					//layout: "horizontal"
				},
				sIcon : {
					image : '/oilsthumbs/soicon' + iconCount + '.png',
				},
				sName : {
					text : data[i].NAME,
				},
				sAffinity : {
					text : "Affinitive For: " + data[i].AFFINITY_FOR
				}
			});

		}

	}

	section.appendItems(dataItem);
	sections.push(section);
	$.singleList.sections = sections;

}

It would be a great favor if you could answer the following question:
When "myLoader" is triggered (called) ? 
Also can you explain a test case that uses one of the available functions ? 
In the mentioned code of this comment If myLoader is called every time I reach at the end of the page then it should load 10 items at each end but it is not it loads only first time. What I am doing wrong? 
I would really appreciate any help.

**Comment by FokkeZB** [comment]
Hi @mnadeemughal 

The thing is; all this widget does is get you an `end` event when the end of the list is reached. What happen then is totally up to you. If you don't want all of that JSON data to show at once you will need to cut it in pages and initially only show the first page. Then every time you get the event you should use `appendItems` to add the next page of items.

**Comment by mnadeemughal** [comment]
Hi FokkeZB, 
Thank you again for responding the query. 
I get what you have explained in your recent comment. If you understand my previous comment(code part) carefully I have divided the data into pages(10-items per page). And trying to load page by page as you have told. But it only loads first 10items then it doesn't load more. Can you take a care look at the previous comment ?

My second question is "myLoader" is called every time it reaches the end of the items ?

**Comment by FokkeZB** [comment]
Sorry I missed that. So the `j` var is updated somewhere after each time `myLoader` is called? I don't see that happening anywhere?

`myLoader` will be called every time the user reaches the end of the list indeed. Just put a log call in it to verify.

**Comment by mnadeemughal** [comment]
Yes 'j' is updated at the end of "myLoader" function. See updated code in same comment. 
I have shown alert at the start of myLoader to check wether it is called everytime but it doesn't.

**Comment by FokkeZB** [comment]
Ah, sorry I missed that. Maybe the problem is you're re-setting the sections every time. Do you want to create a new section for each "page" or is your idea to keep all items in the same section? If you keep them in the same section I'd create the section in the XML, give it an idea and then in your controller use `$.sectionId.appendItems(items)`. If you need a new section for each "page" then create the section, use `setItems` on that section and then use `appendSection()` on the list to add the section.
