### ISSUE TITLE
undefined is not an object (evaluating 'Ti.UI.ActivityIndicatorStyle.DARK')

### ISSUE THREAD

**Issue by mjstelly** [FokkeZB/nl.fokkezb.infiniteScroll#53]
Had to make a few updates to the code (tiapp.xml and replace iphone ai style). However, it didn't fix the crash.

Running ios sim (iPhone 5s; ios 8.3, sdk 3.5.1.GA), still getting same error 
`[ERROR] Script Error {
[ERROR]     column = 44;
[ERROR]     line = 150;
[ERROR]     message = "undefined is not an object (evaluating 'Ti.UI.ActivityIndicatorStyle.DARK')";
[ERROR]     sourceURL = "file:///Users/mjstelly/Library/Developer/CoreSimulator/Devices/869608B4-D439-4739-A61C-A523254FCBD3/data/Containers/Bundle/Application/6B7AEC71-F057-4147-A6B2-BBDF4448AA47/test.app/alloy/widgets/nl.fokkezb.infiniteScroll/controllers/widget.js";`

The offending line in the compiled code is:
`    $.__views.isIndicator = Ti.UI.createActivityIndicator({
        style: Ti.UI.ActivityIndicatorStyle.DARK,
        id: "isIndicator"
    });`

Not really sure what's causing this problem.

**Comment by FokkeZB** [comment]
This is because [Ti.UI.ActivityIndicatorStyle](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.ActivityIndicatorStyle-property-DARK) is available from SDK 5.1.0

If you work with an older SDK, please override the style to use `Ti.UI.iPhone.ActivityIndicatorStyle.DARK`
