### ISSUE TITLE
There's a way to block?

### ISSUE THREAD

**Issue by DouglasHennrich** [FokkeZB/nl.fokkezb.infiniteScroll#54]
I'm using your pull to request widget as well and when I pull to refresh, it trigged twice, one for pull to refresh and another to load more.

There's a way to block my infinityScroll ?

**Comment by FokkeZB** [comment]
You can use the `detach()` on either to disable. What I mostly did is wait to `init()` the infinite scroll widget until after the first page has loaded, since if the list is empty it will be triggered because the end of the list is reached.

**Comment by DouglasHennrich** [comment]
Thanks I will try that
