### ISSUE TITLE
Enhancement request - any plans to add "reverse scrolling" similar to a typical chat app?

### ISSUE THREAD

**Issue by parijatsahai** [FokkeZB/nl.fokkezb.infiniteScroll#57]
Is there any plan to add infinite "reverse scrolling" similar to the standard chat apps? This would be a real boon. I can't find a way to perform reverse scrolling (automatically loading the rows on top instead of bottom) that prevents the tableview or listview from automatically scrolling when a new row is inserted on top (a really undesirable behavior).

**Comment by FokkeZB** [comment]
Isn't that what the pull to refresh control is for? I guess you could appendSections/Items and use the [animated](http://docs.appcelerator.com/platform/latest/#!/api/ListViewAnimationProperties) property to not let it scroll? I dunno, play with it. I'm open to PRs.

**Comment by parijatsahai** [comment]
The pull to refresh control appends rows to the bottom of the tableview/listview. What I'm looking for is a functionality common in chat apps where when you scroll up, the message load at the top, i.e., they are inserted above the existing rows. Using Titanium, I have been unable to achieve this functionality successfully because as soon as I insert a row above the first row, Titanium automatically scrolls the inserted row into the viewable area of the screen. However, what I want is to insert the rows "in the background" above the viewable area of the screen so that the scrolling upwards is seamless to the user.

**Comment by parijatsahai** [comment]
I just realized that my request is identical to the previous issue #50 opened earlier!

**Comment by FokkeZB** [comment]
Hey, indeed ;)

But you might want to create a JIRA ticket as well since it looks like we need adjustments in the SDK.

**Comment by parijatsahai** [comment]
JIRA ticket [TC-5899](https://jira.appcelerator.org/browse/TC-5899) created.
