### ISSUE TITLE
Add To List and Rest List

### ISSUE THREAD

**Issue by daudirsch** [FokkeZB/nl.fokkezb.infiniteScroll#60]
First, thanks for your work on both Pull to Refresh and Infinite Scroll, they have helped greatly.  I can't quite figure out 2 things though.  

Whenever it loads the next page of results it resets the table so I only see 10 records at a time (instead of keeping the 10 items from page 1 and adding to it).  I have set collection.fetch({ add:true }), which is what I thought would do it.  

Second question, how do you reset the page index so that I can reload the table with just the first page of results?  I tried to calling $.tableWidget.load(); but it just reloads the current page.  Is there a currentIndex or something?  Or do I need to detach and re-initialize/load the Infinite Scroll module?

Sorry for 2 questions in one post but I know you don't work on this often and only wanted to bug you once.  :)  Thanks again for the work.

**Comment by FokkeZB** [comment]
I think it's important to understand that all this widget does is fire an event when the list reaches its end or when you call `load()`. What happens after that is up to you. Indeed `add:true` should only append to a collection, not replace it. Why it doesn't work that way in your codebase is not related to the widget.

You could use a widget like pullToRefresh (link in the readme) to reset whatever kind of paging you work with. But again, that widget will simply add a refresh control to the list and fire an event when it is used. Everything else is up to you.
