### ISSUE TITLE
IOS error

### ISSUE THREAD

**Issue by ramontavarez** [FokkeZB/nl.fokkezb.infiniteScroll#67]
I got this problem when i tried to build my app for ios (in android it works well)

![image](https://user-images.githubusercontent.com/10215019/92559306-b5cd8900-f246-11ea-97d9-0b7eca41c90c.png)

**Comment by ramontavarez** [comment]
sorry, it's because i used the new version of titanium sdk on mac.
anyway, it's a problem with the new version of titanium sdk (9.1.0.GA)

**Comment by Topener** [comment]
Thanks for pointing out a bug! I will have a look

**Comment by jeffmetanna** [comment]
It looks like the SDK 9.X is throwing this error when you attach a method named "init" to a controller and try to call it. I extensively use this method throughout my app and I get a bunch of errors like this. When I rename the method to something else like "initialize", it works fine. 

I don't know if the method "init" is now a system reserved one or not but it's not mentioned in the release note.

**Comment by energy2080** [comment]
I have the same error. Changing to "initialize doesnt work for me". This issue is only with IOS

**Comment by ramontavarez** [comment]
i tried to update the sdk version to 9.1.0.GA on my tiapp.xml and build it to android and got the same error.
i dont know why but when i tried to rollback to 8.3.0.GA version im still getting the same error...
im already tried to delete all folders like "build", "platform" etc but im still getting the error.

Here's the stacktrace (in this case i tried to rename the init methods to initiate but getting the same error):
```
[ERROR] TiExceptionHandler: (main) [42,7543]   infiniteCallback ? $.__views["is"].on('end', infiniteCallback) : __defers['$.__views["is"]!end!infiniteCallback'] = true;var __alloyId321 = {};var __alloyId323 = Alloy.createController('cards/standard', { apiName: "Alloy.Require", classes: [], __itemTemplate: __alloyId321 }).getViewEx({ recurse: true });
[ERROR] TiExceptionHandler:                                      ^
[ERROR] TiExceptionHandler: TypeError: Cannot read property 'on' of null
[ERROR] TiExceptionHandler:     at new Controller (eval at Module._compile (/app.js:727:16), <anonymous>:45:38)
[ERROR] TiExceptionHandler:     at Object.exports.createController (eval at Module._compile (/app.js:727:16), <anonymous>:430:10)
[ERROR] TiExceptionHandler:     at new Controller (eval at Module._compile (/app.js:727:16), <anonymous>:40:59)
[ERROR] TiExceptionHandler:     at Object.exports.createController (eval at Module._compile (/app.js:727:16), <anonymous>:430:10)
[ERROR] TiExceptionHandler:     at success (eval at Module._compile (/app.js:727:16), <anonymous>:66:23)
[ERROR] TiExceptionHandler:     at Object.options.success (eval at Module._compile (/app.js:727:16), <anonymous>:763:22)
[ERROR] TiExceptionHandler:     at Object.Sync [as sync] (eval at Module._compile (/app.js:727:16), <anonymous>:275:43)
[ERROR] TiExceptionHandler:     at child.extendObj.sync (eval at Module._compile (/app.js:727:16), <anonymous>:184:18)
[ERROR] TiExceptionHandler:     at child.fetch (eval at Module._compile (/app.js:727:16), <anonymous>:766:43)
[ERROR] TiExceptionHandler:     at initApp (eval at Module._compile (/app.js:727:16), <anonymous>:59:10)
[ERROR] TiExceptionHandler:
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Function.nativeInvoke(Native Method)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Function.callSync(V8Function.java:55)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Function.call(V8Function.java:41)
[ERROR] TiExceptionHandler:     ti.modules.titanium.TitaniumModule$Timer.run(TitaniumModule.java:167)
[ERROR] TiExceptionHandler:     android.os.Handler.handleCallback(Handler.java:873)
[ERROR] TiExceptionHandler:     android.os.Handler.dispatchMessage(Handler.java:99)
[ERROR] TiExceptionHandler:     android.os.Looper.loop(Looper.java:193)
[ERROR] TiExceptionHandler:     android.app.ActivityThread.main(ActivityThread.java:6669)
[ERROR] TiExceptionHandler:     java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiExceptionHandler:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[ERROR] V8Exception: Exception occurred at undefined:45: Uncaught TypeError: Cannot read property 'on' of null
```

**Comment by energy2080** [comment]
I tried to rollback the sdk as well. Still same problem. I now see it on android as well.

**Comment by energy2080** [comment]
Im not sure why this works. Could be an issue with FooterView, but if I take the Widget out of the TableView and place it beneath.... All is well

`<TableView id="tableList" class="tableSet" separatorStyle="none"></TableView>
<Widget id="is" src="nl.fokkezb.infiniteScroll" onEnd="myLoader" />`

**Comment by Topener** [comment]
Looks like this is a bug with the require tag that will be resolved, hopefully, today, with a new CLI release: https://jira.appcelerator.org/browse/ALOY-1738.

Therefore, closing the ticket. Thanks everyone!
